# Generated by Django 6.0 on 2026-01-25 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfexLeadSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfex_lead_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, default='', help_text='Hash of last successfully synced payload for idempotency.', max_length=64)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfex_sync', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='crm_integra_status_fc9adc_idx'), models.Index(fields=['perfex_lead_id'], name='crm_integra_perfex__fcc7db_idx')],
            },
        ),
    ]
