# Generated by Django 6.0 on 2026-01-25 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, default='', help_text='Optional source-specific identifier (listing id, etc.).', max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_raw', models.CharField(blank=True, default='', max_length=64)),
                ('phone_e164', models.CharField(blank=True, default='', help_text='Normalized E.164 number', max_length=32)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO-3166 alpha-2', max_length=2)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_text', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of canonicalized raw_payload for dedupe/idempotency.', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('synced', 'Synced'), ('error', 'Error')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'), models.Index(fields=['phone_e164'], name='leads_lead_phone_e_6f7a57_idx'), models.Index(fields=['source_name', 'source_ref'], name='leads_lead_source__04b1ee_idx')],
            },
        ),
    ]
