# Generated by Django 6.0 on 2026-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='default_language',
            field=models.CharField(blank=True, default='', help_text="Default language code (e.g., 'en', 'es')", max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated lead value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Job title/position', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Website URL'),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
