# Generated by Django 6.0 on 2026-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_restructure_lead_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_status_e23abe_idx',
            old_name='leads_lead_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_event_d_ba79e8_idx',
            old_name='leads_lead_event_date_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='event_name',
            field=models.CharField(blank=True, default='', help_text='Name of the event or meeting that was scraped.', max_length=255),
        ),
    ]
