# Generated by Django 6.0 on 2026-02-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_split_prospect_and_lead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_prospec_f41014_idx',
            old_name='leads_lead_prospect_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='leads_prosp_email_a3e203_idx',
            old_name='leads_prospect_email_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='leads_prosp_phone_e_6dbb15_idx',
            old_name='leads_prospect_phone_e164_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='leads_prosp_source__fb84f1_idx',
            old_name='leads_prospect_source_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='leads_prosp_status_8b6833_idx',
            old_name='leads_prospect_status_idx',
        ),
    ]
