# Generated by Django 5.2.11 on 2026-02-21 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('prospect_created', 'Prospect Created'), ('prospect_contacted', 'Prospect Marked Contacted'), ('prospect_converted', 'Prospect Converted to Lead'), ('prospect_rejected', 'Prospect Rejected'), ('lead_created', 'Lead Created'), ('lead_interested', 'Lead Marked Interested'), ('lead_synced', 'Lead Synced to CRM'), ('lead_rejected', 'Lead Rejected'), ('target_created', 'Target Created'), ('target_updated', 'Target Updated'), ('target_enabled', 'Target Enabled'), ('target_disabled', 'Target Disabled'), ('scrape_triggered', 'Scrape Triggered'), ('scrape_completed', 'Scrape Completed'), ('scrape_failed', 'Scrape Failed')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_a_created_f2d914_idx'), models.Index(fields=['action', 'object_type'], name='dashboard_a_action_b62bd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_n_user_id_5c2164_idx'), models.Index(fields=['user', 'read'], name='dashboard_n_user_id_fed4e3_idx')],
            },
        ),
    ]
