# Generated by Django 5.2.11 on 2026-03-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discovery_query', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('search', 'Search Engine'), ('directory', 'Directory'), ('event_platform', 'Event Platform'), ('ngo_directory', 'NGO Directory')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'priority'], name='crawler_cra_enabled_48549e_idx'), models.Index(fields=['source_type', 'enabled'], name='crawler_cra_source__0e58fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('crawl_attempts', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(default=5)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='crawler.crawlsource')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, default='', max_length=255)),
                ('org_type', models.CharField(blank=True, default='', max_length=100)),
                ('detected_org_types', models.JSONField(default=list)),
                ('detected_services', models.JSONField(default=list)),
                ('languages_detected', models.JSONField(default=list)),
                ('countries_detected', models.JSONField(default=list)),
                ('international_signals', models.JSONField(default=list)),
                ('event_names', models.JSONField(default=list)),
                ('contact_emails', models.JSONField(default=list)),
                ('contact_phones', models.JSONField(default=list)),
                ('translation_need_score', models.IntegerField(default=0)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='crawler.discovereddomain')),
            ],
        ),
        migrations.AddIndex(
            model_name='discovereddomain',
            index=models.Index(fields=['crawl_status', 'priority'], name='crawler_dis_crawl_s_132cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='discovereddomain',
            index=models.Index(fields=['next_attempt_at'], name='crawler_dis_next_at_532baf_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteprofile',
            index=models.Index(fields=['translation_need_score'], name='crawler_web_transla_b77cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteprofile',
            index=models.Index(fields=['analyzed_at'], name='crawler_web_analyze_5b3c78_idx'),
        ),
    ]
