# Generated by Django 5.2.11 on 2026-03-15 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_seed_sources_and_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_text', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Snapshot for this run (max_domains_per_run, etc.)')),
                ('domains_queued', models.PositiveIntegerField(default=0)),
                ('prospects_created', models.PositiveIntegerField(default=0)),
                ('prospects_updated', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='crawler_cra_status_6792b1_idx'), models.Index(fields=['-started_at'], name='crawler_cra_started_5a3653_idx')],
            },
        ),
    ]
