# Generated by Django 5.2.11 on 2026-03-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawl_run_domain_result'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crawlrundomainresult',
            new_name='crawler_cra_run_id_920198_idx',
            old_name='crawler_cra_run_id_89a6b7_idx',
        ),
        migrations.RenameIndex(
            model_name='crawlrundomainresult',
            new_name='crawler_cra_process_70a404_idx',
            old_name='crawler_cra_process_e2896e_idx',
        ),
    ]
