# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0003_add_crawl_run"),
        ("crawler", "0004_rename_crawler_cra_run_id_89a6b7_idx_crawler_cra_run_id_920198_idx_and_more"),
    ]

    operations = []
