# Generated by Django 5.2.11 on 2026-03-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawlrundomainresult_crawl_run'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crawlrundomainresult',
            new_name='crawler_cra_crawl_r_5b375a_idx',
            old_name='crawler_cra_crawl_r_state_idx',
        ),
    ]
