# Generated by Django 6.0 on 2026-01-25 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('target_type', models.CharField(choices=[('html', 'HTML (requests/bs4)'), ('playwright', 'Playwright (browser automation)')], default='html', max_length=20)),
                ('start_url', models.URLField()),
                ('run_every_minutes', models.PositiveIntegerField(default=60, help_text='Beat schedule interval (minutes).')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_text', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_leads', models.PositiveIntegerField(default=0)),
                ('updated_leads', models.PositiveIntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scraper.scrapetarget')),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'started_at'], name='scraper_scr_target__453518_idx')],
            },
        ),
    ]
