"""
Django settings for leads_app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from __future__ import annotations

import json
import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# (Path already imported above)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _get_env(name: str, default: str | None = None) -> str | None:
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return value


def _get_bool(name: str, default: bool = False) -> bool:
    value = _get_env(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def _get_list(name: str, default: list[str] | None = None) -> list[str]:
    value = _get_env(name)
    if value is None:
        return default or []
    # allow JSON list or comma-separated
    value = value.strip()
    if value.startswith("["):
        try:
            parsed = json.loads(value)
            return [str(x).strip() for x in parsed if str(x).strip()]
        except json.JSONDecodeError:
            pass
    return [part.strip() for part in value.split(",") if part.strip()]


def _parse_database_url(database_url: str):
    """
    Minimal DATABASE_URL parser (Postgres + SQLite) to avoid extra deps.

    Examples:
      - postgres://user:pass@host:5432/dbname
      - postgresql://user:pass@host:5432/dbname?sslmode=require
      - sqlite:///absolute/path/db.sqlite3
      - sqlite:///./relative.sqlite3
    """
    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    if scheme in {"postgres", "postgresql"}:
        options = parse_qs(parsed.query)
        conn_max_age = int(_get_env("DB_CONN_MAX_AGE", "60") or "60")

        # Support percent-encoded usernames/passwords
        user = unquote(parsed.username or "")
        password = unquote(parsed.password or "")

        db = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (parsed.path or "").lstrip("/"),
            "USER": user,
            "PASSWORD": password,
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
            "CONN_MAX_AGE": conn_max_age,
        }

        # sslmode mapping (common on PaaS)
        sslmode = (options.get("sslmode") or options.get("ssl") or [None])[0]
        if sslmode:
            db.setdefault("OPTIONS", {})
            db["OPTIONS"]["sslmode"] = sslmode

        return db

    if scheme == "sqlite":
        # sqlite:///./db.sqlite3  -> path like "/./db.sqlite3"
        path = unquote(parsed.path or "")
        if path.startswith("/./"):
            name = str(BASE_DIR / path[3:])
        elif path.startswith("/") and len(path) > 1:
            name = path[1:]
        else:
            name = str(BASE_DIR / "db.sqlite3")
        return {"ENGINE": "django.db.backends.sqlite3", "NAME": name}

    raise ValueError(f"Unsupported DATABASE_URL scheme: {scheme!r}")


# Load .env for local/dev convenience (no-op in real PaaS)
try:
    from dotenv import load_dotenv  # type: ignore

    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_env(
    "DJANGO_SECRET_KEY",
    # dev-only fallback (must not be used with DEBUG=False)
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = _get_list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

ENVIRONMENT = _get_env("DJANGO_ENV", "development" if DEBUG else "production")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local apps
    'core',
    'leads',
    'scraper',
    'crm_integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise is optional; enables simple static serving in production.
    # If not installed, we safely skip it.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'leads_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leads_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = _get_env("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {"default": _parse_database_url(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = _get_env("DJANGO_TIME_ZONE", "UTC") or "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = _get_env("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")) or str(
    BASE_DIR / "staticfiles"
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Security hardening (safe defaults for production) ---
if not DEBUG:
    if SECRET_KEY == "django-insecure-dev-only-change-me":
        raise RuntimeError("DJANGO_SECRET_KEY must be set in production (DEBUG=False).")

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _get_bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = _get_bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = _get_bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
    SECURE_HSTS_SECONDS = int(_get_env("DJANGO_SECURE_HSTS_SECONDS", "3600") or "3600")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
    )
    SECURE_HSTS_PRELOAD = _get_bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = _get_env("DJANGO_SECURE_REFERRER_POLICY", "same-origin")
    X_FRAME_OPTIONS = _get_env("DJANGO_X_FRAME_OPTIONS", "DENY")

CSRF_TRUSTED_ORIGINS = _get_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

# --- Optional WhiteNoise ---
try:
    import whitenoise  # type: ignore  # noqa: F401

    if "whitenoise.middleware.WhiteNoiseMiddleware" not in MIDDLEWARE:
        MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
except Exception:
    pass

# --- Logging / Observability ---
LOG_LEVEL = (_get_env("DJANGO_LOG_LEVEL", "INFO") or "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
}

try:
    import structlog  # type: ignore  # noqa: F401

    # Minimal structlog setup; Django LOGGING still works.
    structlog.configure(
        processors=[
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.add_log_level,
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.JSONRenderer(),
        ]
    )
except Exception:
    pass

SENTRY_DSN = _get_env("SENTRY_DSN")
if SENTRY_DSN:
    try:
        import sentry_sdk  # type: ignore
        from sentry_sdk.integrations.django import DjangoIntegration  # type: ignore

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=ENVIRONMENT,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(_get_env("SENTRY_TRACES_SAMPLE_RATE", "0") or "0"),
            send_default_pii=_get_bool("SENTRY_SEND_DEFAULT_PII", default=False),
        )
    except Exception:
        # If Sentry misconfigures, don't kill the app.
        pass

# --- Celery ---
REDIS_URL = _get_env("REDIS_URL", "redis://localhost:6379/0") or "redis://localhost:6379/0"
CELERY_BROKER_URL = _get_env("CELERY_BROKER_URL", REDIS_URL) or REDIS_URL
CELERY_RESULT_BACKEND = _get_env("CELERY_RESULT_BACKEND", REDIS_URL) or REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_QUEUE = _get_env("CELERY_DEFAULT_QUEUE", "default") or "default"

# Periodic tasks (can be tuned via env)
CELERY_BEAT_SCHEDULE = {
    "scrape-enabled-targets": {
        "task": "scraper.tasks.enqueue_enabled_targets",
        "schedule": timedelta(
            seconds=int(_get_env("SCRAPE_ALL_INTERVAL_SECONDS", "300") or "300")
        ),
    },
    "perfex-sync-pending": {
        "task": "crm_integration.tasks.sync_pending_to_perfex",
        "schedule": timedelta(
            seconds=int(_get_env("PERFEX_SYNC_INTERVAL_SECONDS", "60") or "60")
        ),
    },
}
